//! TECH — 104.7 MHz
//!
//! Reference implementation station. Engineering blogs, deep-dive writeups,
//! primary sources. HN >= 150 points, lobste.rs >= 10 votes.
//!
//! This is the smoke test for the SDK and the WIT interface.
//! If this compiles and runs, the architecture works.

// `bindings` is generated by cargo-component during build.
// Build with: cargo component build --target wasm32-wasip2
#[allow(warnings)]
mod bindings;

use bindings::exports::radio::station::station::{Broadcast, Guest, Metadata, Signal};
use salvage_sdk::{html_to_text, Cache, Result, parse_rss};

struct TechStation;

impl Guest for TechStation {
    fn describe() -> Metadata {
        Metadata {
            callsign: "TECH".to_string(),
            name: "Tech".to_string(),
            description:
                "Engineering deep-dives. HN >= 150 points, lobste.rs >= 10 votes.".to_string(),
            frequency: "104.7".to_string(),
            operator: "Pete".to_string(),
            cadence_seconds: 600,
            declared_hosts: vec!["hnrss.org".to_string(), "lobste.rs".to_string()],
        }
    }

    fn tune() -> Signal {
        let cache = Cache::new();
        let last_seen: Vec<String> = cache.get_json("last_seen").unwrap_or_default();

        let items = match fetch_all() {
            Ok(items) => items,
            Err(e) => return Signal::OffAir(format!("fetch failed: {e}")),
        };

        let fresh: Vec<_> = items
            .into_iter()
            .filter(|i| !last_seen.contains(&i.id))
            .collect();

        match fresh.into_iter().next() {
            Some(item) => {
                let mut new_seen = last_seen;
                new_seen.push(item.id.clone());
                new_seen.truncate(200);
                cache.set_json("last_seen", &new_seen);

                Signal::OnAir(Broadcast {
                    id: item.id,
                    title: item.title,
                    body: html_to_text(&item.body_html),
                    source: item.source_name,
                    permalink: item.permalink,
                    published: item.published,
                    tags: vec!["tech".to_string()],
                })
            }
            None => Signal::Static,
        }
    }
}

fn fetch_all() -> Result<Vec<salvage_sdk::RawItem>> {
    let hn = salvage_sdk::http::fetch("https://hnrss.org/frontpage?points=150")?;
    let lo = salvage_sdk::http::fetch("https://lobste.rs/rss")?;

    let mut items = parse_rss(&hn)?;
    items.extend(parse_rss(&lo)?);
    items.sort_by_key(|i| std::cmp::Reverse(i.published));
    Ok(items)
}

bindings::export!(TechStation with_types_in bindings);
